
package ru.fireway.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountWebServiceImplService", targetNamespace = "http://ws.fireway.ru/", wsdlLocation = "http://localhost:1986/wss/account?wsdl")
public class AccountWebServiceImplService
    extends Service
{

    private final static URL ACCOUNTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.fireway.ru/", "AccountWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/wss/account?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AccountWebServiceImplService() {
        super(__getWsdlLocation(), ACCOUNTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AccountWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AccountWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AccountWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AccountWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountWebService
     */
    @WebEndpoint(name = "AccountWebServiceImplPort")
    public AccountWebService getAccountWebServiceImplPort() {
        return super.getPort(new QName("http://ws.fireway.ru/", "AccountWebServiceImplPort"), AccountWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountWebService
     */
    @WebEndpoint(name = "AccountWebServiceImplPort")
    public AccountWebService getAccountWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fireway.ru/", "AccountWebServiceImplPort"), AccountWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
