
package ru.fireway.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountWebService", targetNamespace = "http://ws.fireway.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AccountWebService {


    /**
     * 
     * @param id
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.fireway.ru/AccountWebService/getAmountRequest", output = "http://ws.fireway.ru/AccountWebService/getAmountResponse")
    Long getAmount(
        @WebParam(name = "id", partName = "id")
        Integer id);

    /**
     * 
     * @param value
     * @param id
     */
    @WebMethod
    @Action(input = "http://ws.fireway.ru/AccountWebService/addAmountRequest", output = "http://ws.fireway.ru/AccountWebService/addAmountResponse")
    void addAmount(
        @WebParam(name = "id", partName = "id")
        Integer id,
        @WebParam(name = "Long", partName = "Long")
        Long value);

}
